solution/app/models.py
import os

from flask import current_app as app

from hurry.filesize import size as human_friendly_size

from . import db


class BaseModel(db.Model):
    """
    Abstract base model.
    """
    __abstract__ = True
    id = db.Column(db.Integer, primary_key=True)
    created_at = db.Column(db.DateTime, default=db.func.current_timestamp())
    updated_at = db.Column(db.DateTime, default=db.func.current_timestamp(), onupdate=db.func.current_timestamp)


class Enquiry(BaseModel):
    """
    An enquiry made by a traveller.
    """
    first_name = db.Column(db.String(120), nullable=False)
    last_name = db.Column(db.String(120), nullable=False)
    date_of_birth = db.Column(db.Date, nullable=False)
    passenger_count = db.Column(db.Integer, nullable=False)
    email = db.Column(db.String(120), nullable=False)
    price = db.Column(db.Integer, nullable=False)

    def __repr__(self):
        return '<Enquiry {} {} {}>'.format(self.id, self.first_name, self.last_name)


class EnquiryConfirmation(BaseModel):
    """
    A confirmation for an enquiry in pdf format.
    """
    name = db.Column(db.String(255), unique=True, nullable=False)
    blob = db.Column(db.LargeBinary(), nullable=False)
    size = db.Column(db.Integer, nullable=False)

    enquiry_id = db.Column(db.Integer, db.ForeignKey('enquiry.id'), nullable=False)
    enquiry = db.relationship('Enquiry', backref=db.backref('confirmations', lazy=True))

    def __repr__(self):
        return '<PdfFile {}, {}>'.format(self.id, self.name)

    @property
    def path(self):
        return os.path.join(app.config['UPLOAD_DIR'], self.name)

    @property
    def upload_date(self):
        return self.created_at.strftime('%Y-%m-%d')

    @property
    def filesize(self):
        return human_friendly_size(self.size)

solution/app/__init__.py
import os

from flask import Flask

from flask_sqlalchemy import SQLAlchemy


db = SQLAlchemy()


def create_app():
    app = Flask(__name__)

    app.config.from_object('config.Config')

    if not os.path.exists(app.config['UPLOAD_DIR']):
        os.makedirs(app.config['UPLOAD_DIR'])

    db.init_app(app)

    from .views import app_blueprint
    app.register_blueprint(app_blueprint)

    return app

solution/app/views.py
from io import BytesIO

from flask import Blueprint, render_template, send_file, request
from flask import current_app as app

from .models import Enquiry, EnquiryConfirmation

app_blueprint = Blueprint('app', __name__)


@app_blueprint.route('/')
def get_confirmations():
    """
    Show a paginated table of enquiry confirmations with the option to filter
    by enquiry id.

    :url-param pk: The enquiry id to query for
    :url-param page: The number of the page to get
    """
    pk = request.args.get('pk', default=None, type=int)
    page = request.args.get('page', default=1, type=int)
    per_page = app.config['PER_PAGE']
    if pk:
        query = EnquiryConfirmation.query.join(Enquiry).filter(Enquiry.id == pk)
    else:
        query = EnquiryConfirmation.query
    confirmations = query \
        .order_by(EnquiryConfirmation.created_at.desc()) \
        .paginate(page, per_page, error_out=False)
    return render_template(
        'index.html',
        pk=pk,
        confirmations=confirmations
    )


@app_blueprint.route('/download/<int:pk>')
def download_confirmation(pk):
    """
    Download an enquiry confirmation pdf file by its id.

    :param pk: The id of the enquiry confirmation
    """
    confirmation = EnquiryConfirmation.query.get(pk)
    filename = confirmation.name
    file = BytesIO(confirmation.blob)
    return send_file(
        file,
        attachment_filename=filename,
        mimetype='application/pdf',
        as_attachment=True
    )

solution/app/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">

    <title>{{ config['APP_TITLE'] }}</title>
</head>
<body>

{% include 'navbar.html' %}

<main class="container">
    {% block content %}{% endblock %}
</main>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

solution/app/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th scope="col">Enquiry id</th>
                <th scope="col">Upload Date</th>
                <th scope="col">Size</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% if confirmations.items|length %}
                {% for row in confirmations.items %}
                    <tr>
                        <td>{{ row.enquiry.id }}</td>
                        <td>{{ row.upload_date }}</td>
                        <td>{{ row.filesize }}</td>
                        <td class="text-center">
                            <a href="{{  url_for('app.download_confirmation', pk=row.id) }}" role="button" class="btn btn-sm btn-outline-info">Download</a>
                        </td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="4" class="text-center">Sorry, no results</td>
                </tr>
            {% endif %}
        </tbody>
    </table>

    {% if confirmations.items|length %}
        <nav class="d-flex justify-content-center">
            <ul class="pagination">
                <li class="page-item {{ 'disabled' if confirmations.page == 1 }}">
                    <a class="page-link" href="{{ url_for('app.get_confirmations', page=1, pk=pk) }}">&laquo;</a>
                </li>
                <li class="page-item {{ 'disabled' if not confirmations.has_prev }}">
                    <a class="page-link" href="{{ url_for('app.get_confirmations', page=confirmations.prev_num, pk=pk) }}">&lsaquo;</a>
                </li>
                <li class="page-item {{ 'disabled' if not confirmations.has_next }}">
                    <a class="page-link" href="{{ url_for('app.get_confirmations', page=confirmations.next_num, pk=pk) }}">&rsaquo;</a>
                </li>
                <li class="page-item {{ 'disabled' if confirmations.page == confirmations.pages }}">
                    <a class="page-link" href="{{ url_for('app.get_confirmations', page=confirmations.pages, pk=pk) }}">&raquo;</a>
                </li>
            </ul>
        </nav>
    {% endif %}
{% endblock %}

solution/app/templates/navbar.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="{{ url_for('app.get_confirmations') }}">{{ config['APP_TITLE'] }}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" data-_extension-text-contrast="">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <div class="ml-auto mt-2 mt-md-0">
            {% include 'search_form.html' %}
        </div>
    </div>
</nav>

solution/app/templates/search_form.html
<form id="search-form" class="form-inline" action="{{ url_for('app.get_confirmations') }}">
    <input class="form-control mr-sm-2" placeholder="Enquiry id" name="pk" type="text">
    <input class="btn btn-outline-success my-2 my-sm-0" type="submit" value="Search">
</form>